baseURL = "http://johnsigmon.me/"
languageCode = "en-us"
title = "John Sigmon"
theme = "hugo-goa"

[[menu.main]]
name = "about"
identifier = "about"
weight = 200
url = "/about/"

[[menu.main]]
name = "writing"
identifier = "writing"
weight = 200
url = "/writing/"

[[menu.main]]
name = "technical writing"
identifier = "technical-writing"
weight = 200
url = "/technical-writing/"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
staticDir = "static"

author = "John Sigmon"
title = "John Sigmon"

## Site Settings
[params]
author = "John Sigmon"
intro = "Engineer"
#description = "Description here"
authorimage = "redrock.jpg"
dateformat = "Jan 2, 2006"

## Social Accounts
[params.social]
github = "jsigee87"
instagram = "jhnsigmon"
linkedin = "john-sigmon"
twitter = "JohnSigmon"
#goodreads = "<username>"
#strava = "<username>"
email = "johnsigmon@gmail.com"
